title: Milli 
baseurl: /
permalink: '/:title/'
collections:
  posts:
    permalink: '/posts/:title/'
description: Milli is a consortium of individuals and communities interested in the nurturing of archives. Archives enable diverse stories.
layout_style: grid
palette: green
header:
  title: Milli Archives Discussion
  logo_img: images/logo.png
  has_nav: true
  nav_links:
    - label: Home
      url: /
      type: link
    - label: About
      url: /about/
      type: link
    - label: IAW2020
      url: /iaw2020/
      type: link
    - label: Contact
      url: /contact/
      type: link
    - label: Join Us
      url: /join-us/
      type: link
footer:
  content: '&copy; All rights reserved.'
  links:
    - label: Made with ❤️
      url: 'https://janastu.org'
      type: link
      new_window: true
  has_social: false
  social_links:
    - label: Twitter
      url: 'https://twitter.com/'
      type: icon
      icon_class: fa-twitter
      new_window: true
    - label: Instagram
      url: 'https://www.instagram.com/'
      type: icon
      icon_class: fa-instagram
      new_window: true
    - label: GitHub
      url: 'https://github.com/'
      type: icon
      icon_class: fa-github
      new_window: true
    - label: LinkedIn
      url: 'https://www.linkedin.com/'
      type: icon
      icon_class: fa-linkedin
      new_window: true
    - label: DEV
      url: 'https://dev.to/'
      type: icon
      icon_class: fa-dev
      new_window: true
  has_subscribe: true
  subscribe_title: Subscribe for new updates
  subscribe_content: >-
    Subscribe to my email newsletter to receive useful articles and special
    offers. This monthly email is sent out on the first of every month.
sass:
  indentWidth: 4
  style: nested
  precision: 10
plugins:
  - jekyll-menus
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - ssg-build.sh
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
  - stackbit-pull.js
